project_name: wqy
builds:
  -
    id: "wqy"
    binary: wqy
    
    ldflags:
      - -s -w

    env:
      - CGO_ENABLED=0

    goos:
      - linux

    goarch:
      - 386
      - amd64
      - arm
      - arm64
      - mips
      - mipsle
      - mips64
      - mips64le

    goarm:
      - 6
      - 7

    gomips:
      - hardfloat
      - softfloat

    tags:
      - netgo

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
